Exit if sync of db failed running bin/site-sync <user name>.

diff --git a/bin/site-sync b/bin/site-sync
--- a/bin/site-sync
+++ b/bin/site-sync
@@ -10,14 +10,14 @@ HOMEDIR=${PWD}
 
 drush --version || exit $?
 
-# Sync images and grab nightly backup of production database.
+# Sync files and grab the nightly backup of the production database.
 if [ -z "$1" ]
   then
     rsync --update -h --modify-window=5 --stats --progress --delete --compress --recursive --verbose --exclude-from="bin/exclude_elmcip.txt" $SITE:/applications/elmcip.net/drupal/sites/default/files drupal/sites/default
     RESULT=`rsync -L -h --stats --progress --verbose $DB_SITE:/files/latest.elmcip.sql.gz site/`
     if [ $? != 0 ]; then
     {
-      echo "ERROR: problem syncing "
+      echo "ERROR: problem syncing DB"
       echo $RESULT
       exit 1
     }
@@ -25,12 +25,19 @@ if [ -z "$1" ]
   else
     echo "Connecting to $DB_SITE and $SITE as user: $1"
     rsync --update -h --modify-window=5 --stats --progress --delete --compress --recursive --verbose --exclude-from="bin/exclude_elmcip.txt" $1@$SITE:/applications/elmcip.net/drupal/sites/default/files drupal/sites/default
-    rsync -L -h --stats --progress --verbose $1@$DB_SITE:/files/latest.elmcip.sql.gz site/
+    RESULT=`rsync -L -h --stats --progress --verbose $1@$DB_SITE:/files/latest.elmcip.sql.gz site/`
+    if [ $? != 0 ]; then
+    {
+      echo "ERROR: problem syncing DB"
+      echo $RESULT
+      exit 1
+    }
+  fi
 fi
 
 cd $DRUPAL
 
-# Drop all data and populate database with latest backup.
+# Drop all data and populate database with the latest backup.
 drush --uri=$URI sql-drop --yes
 gunzip -c ../site/latest.elmcip.sql.gz | drush --uri=$URI sql-cli
 
